name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: ./flask-server
        run: docker build . --file Dockerfile --tag ricocelsius/nuance-blog-microservice:latest
      - name: Publish
        run: |
          docker login -u ricocelsius -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker push ricocelsius/nuance-blog-microservice:latest
