name: Docker Image CI

on:
  workflow_run:
    branches: ['main']
    workflows: ["Run tests"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: ./
        run: docker build . --file Dockerfile --tag ricocelsius/nuance-blog-microservice:latest
      - name: Publish
        run: |
          docker login -u ricocelsius -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ricocelsius/nuance-blog-microservice:latest
